version: '3'

volumes:
  mqm1:
  mqm2:
  mqm3:
  mqm4:

services:

  qmgr1:
    image: ibmcom/mq:9
    ports:
      - "1414:1414"
      - "9443:9443"
    environment:
      LICENSE: "accept"
      MQ_QMGR_NAME: "QMGR1"
    volumes:
      - mqm1:/mnt/mqm

  qmgr2:
    image: ibmcom/mq:9
    ports:
      - "1415:1414"
      - "10443:9443"
    environment:
      LICENSE: "accept"
      MQ_QMGR_NAME: "QMGR1"
    volumes:
      - mqm2:/mnt/mqm

  qmgr3:
    image: ibmcom/mq:9
    ports:
      - "1416:1414"
      - "11443:9443"
    environment:
      LICENSE: "accept"
      MQ_QMGR_NAME: "QMGR1"
    volumes:
      - mqm3:/mnt/mqm

  qmgr4:
    image: ibmcom/mq:9
    ports:
      - "1417:1414"
      - "12443:9443"
    environment:
      LICENSE: "accept"
      MQ_QMGR_NAME: "QMGR1"
    volumes:
      - mqm4:/mnt/mqm

  ibm-tomcat-camel:
    image: quay.io/eformat/ibmmq-tomcat-camel:latest
    ports:
      - "8080:8080"
      - "9999:9999"
    depends_on:
      - qmgr1
      - qmgr2
      - qmgr3
      - qmgr4

